### ISSUE TITLE
articulo "the unix shell"

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/shell-novice-es#1]
I had initiated a poll to decide whether to keep the terminal as "El terminal" or to change as "La terminal".
We had discussed this already, but now, we need to re-start this discussion with some backup data.
The poll will close feb 22nd. The answer with most votes will be taken. Results will be shared publicly.
Please contribute with your vote
https://goo.gl/forms/M3qiYKkRYwupjlfK2

**Comment by orchid00** [comment]
The poll is now closed if you had filled in your vote you are able to see the summary of responses. https://goo.gl/forms/M3qiYKkRYwupjlfK2 . If you haven't filled the form we received 114 votes and the majority of votes selected "La Terminal" with 86.8% from all the votes. @ErinBecker

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/shell-novice-es/pull/21
