### ISSUE TITLE
missing figure

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/shell-novice-es#32]
this page https://swcarpentry.github.io/shell-novice-es/discuss/ refers to an image that is not in the repository:  https://swcarpentry.github.io/shell-novice-es/fig/x-for-directories.svg

Does anyone know what is it and where we could find it?

**Comment by orchid00** [comment]
Yes I know. 
Its from here: https://liz-fernandez.github.io/PBI_linux_shell/08-permissions/
the image is https://liz-fernandez.github.io/PBI_linux_shell/fig/x-for-directories.svg
there are a some extra episodes contributions by Selene Fernandez, lesson which was shared with us hence we inherited. However, @ErinBecker suggested to leave those extra episodes separated as they are not in the original lesson. 

Would the easiest be to copy over that figure?

Note: I do not have access to Selene's repo but the site is here: https://liz-fernandez.github.io/PBI_linux_shell/

**Comment by fmichonneau** [comment]
great thank you. I added the figure from this repo.
