### ISSUE TITLE
Setup page

### ISSUE THREAD

**Issue by agbeltran** [swcarpentry/shell-novice-es#44]
The setup page is not displaying correctly: https://swcarpentry.github.io/shell-novice-es/setup/

(La página de configuración no se muestra correctamente).

**Comment by agbeltran** [comment]
<img width="657" alt="Screen Shot 2019-04-13 at 17 02 25" src="https://user-images.githubusercontent.com/1417033/56084767-2b44e800-5e0e-11e9-8141-0957c0dab019.png">

**Comment by raynamharris** [comment]
Fixed by removing a permalink (with 351b779)
